const elements = ["tas","kagit","makas"];
const tas = document.getElementById("tas");
const kagit = document.getElementById("kagit");
const makas = document.getElementById("makas");
const secondText = document.getElementById("in-result");
const againButton = document.getElementById("again");
const giveUpButton = document.getElementById("giveup");
const matchResult = document.getElementById("match-result");
const computerImage = document.getElementById("com-choice-image");
const userImage = document.getElementById("user-choice-image");
const userPointImage = document.getElementById("user-number");
const computerPointImage = document.getElementById("com-number");
const setResultText = document.getElementById("result");
const comText = document.getElementById("com");
const userText = document.getElementById("player");
const tempNameInputPlaceHolder = document.getElementById("name-input");
const parentTemp = document.getElementById("parent-temp");
const prizePage = document.getElementById("prize-page");
const claimButton = document.getElementById("claim-button");
const tempPage = document.getElementById("temp");
const playGround = document.getElementById("play-ground");
const englishButton = document.getElementById("en");
const turkishButton = document.getElementById("tr");
const submitButton = document.getElementById("temp-submit"); 
const matchResultText = document.getElementById("result-text");
const mainSetEnglish = document.getElementById("en-main");
const mainSetTurkish = document.getElementById("tr-main");
const prizeAmountText = document.getElementById("prize-amount");
const prizeText = document.getElementById("prize-text");
const userWallet = document.getElementById("wallet");
const metamaskDiv = document.getElementById("metamask-div");
const metamaskButton = document.getElementById("metamask-button");
const metamaskAdressText = document.getElementById("metamask-adress"); 
const betPage = document.getElementById("bet-page");
const increaseButton = document.getElementById("increase-bet-button");
const decreaseButton = document.getElementById("decrease-bet-button");
const betAmountText = document.getElementById("bet-amount");
const estPrizeAmountText = document.getElementById("estimated-prize-amount");
const betApproveButton = document.getElementById("bet-submit-button");
const transferButton = document.getElementById("transfer-button");

let userChoice;
let computerChoice;
let userPoint = 0;
let computerPoint = 0;
let finishCheck = 0;
let startGame = 0;
let drawText;
let setWinText;
let matchWinText;
let computerLanguageText;
let userLanguageText;
let prizeLanguageText;
let claimLanguageText;
let walletLanguageText;
let languageCheck = 0;
let language = "empty";
let winner; 
let prizeAmount;
let claimText;
let betAmount = 0;
let estPrizeAmount = 0;
let userPrize = 100;
let isConnected = 0;
let connectionLanguageText;
let disconnectionLanguageText;
let adressLanguageText;
let isWalletConnected = false;
